version: '3.8'

services:
  db:
    image: postgres:15-bullseye
    container_name: prisma_postgres
    environment:
      POSTGRES_USER: postgres-fapi
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prisma_db
    # Listen on port 5433 inside the container
    command: ["postgres", "-p", "5433"]
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma:
    image: node:18-slim
    container_name: prisma_migration
    working_dir: /app
    volumes:
      - ./prisma:/app/prisma
      - ./backend:/app/backend
    command: >
      sh -c "
      apt-get update &&
      apt install python3.11-venv -y &&
      apt-get install -y python3 python3-pip openssl &&
      python3 -m venv /app/venv &&
      . /app/venv/bin/activate &&
      pip install prisma &&
      npm install -g prisma &&
      prisma generate &&
      prisma db push
      "
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_tfSw7LcHv1Ei@ep-noisy-wind-a8ia9edu-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"
    depends_on:
      - db

  backend:
    build: .
    container_name: prisma_backend
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_tfSw7LcHv1Ei@ep-noisy-wind-a8ia9edu-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - prisma
    volumes:
      - .:/app
    command: >
      sh -c "
      prisma generate &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data: